### ISSUE TITLE
Wrap api for device.uuid

### ISSUE THREAD

**Issue by achtan** [jcesarmobile/IDFVPlugin#4]
so we can call `window.IDFVPlugin.getIdentifier()` and on IOS return `identifier for vendor` and on other devices return `device.uuid`

**Comment by jcesarmobile** [comment]
next version of device plugin will use the identifier for vendor on iOS, so there is no point on adding this now, as soon as the new device plugin is released, this identifier for vendor plugin is dead

**Comment by achtan** [comment]
aha ok, and where is the release ?

**Comment by jcesarmobile** [comment]
The change is already on the github repository, so you can install it with 
cordova plugin add https://github.com/apache/cordova-plugin-device

But I don't know when will be published on npm
