### ISSUE TITLE
does it support ios9 ?

### ISSUE THREAD

**Issue by spali90** [jcesarmobile/IDFVPlugin#5]
On ios9 , for following code, it alerts 'a' but not 'b' and 'error'. 

alert('a');
window.IDFVPlugin.getIdentifier(function(result) {
                alert('b');
                $scope.setDeviceToken(window.localStorage.getItem("deviceToken"), result);
                $scope.localSettings.tokenUpdate = true;
            }, function(error) {
                alert(error);
            });

**Comment by jcesarmobile** [comment]
did you got it working?
what was the problem?

**Comment by spali90** [comment]
Yes, it works. Problem was some where in my code.
